'''
SELECT MONTH(T.START_DATE) AS MONTH, T.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T
LEFT JOIN (SELECT CAR_ID, COUNT(*) AS CNT
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE 1=1
            AND (DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')
            GROUP BY CAR_ID) SUB_T
ON T.CAR_ID = SUB_T.CAR_ID
WHERE 1=1
    AND SUB_T.CNT >= 5
    AND (DATE_FORMAT(T.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;
'''