'''
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE 1=1
    AND C.CAR_TYPE = '세단'
    AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC;
'''

'''
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE 1=1
    AND C.CAR_TYPE = '세단'
    AND H.START_DATE LIKE '%-10-%'
ORDER BY C.CAR_ID DESC;
'''