'''
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE 1=1
    AND ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;
'''

'''
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE 1=1
    AND ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;
'''